version: '3.8'
services:
  web:
    build:
      context: .
    env_file:
      - .env
    command: ["/mylib/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env
volumes:
  postgres_data: