"""1000 symbols

Revision ID: f1afbe2e4a39
Revises: fd6cff5c7185
Create Date: 2023-11-01 20:26:37.956761

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1afbe2e4a39"
down_revision: Union[str, None] = "fd6cff5c7185"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book",
        "annotate",
        existing_type=sa.VARCHAR(length=250),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book",
        "annotate",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
