"""add column pages and rating

Revision ID: fd6cff5c7185
Revises: 78f092779a86
Create Date: 2023-11-01 20:15:56.551723

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd6cff5c7185"
down_revision: Union[str, None] = "78f092779a86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("pages", sa.Integer(), nullable=False))
    op.add_column("book", sa.Column("rating", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "rating")
    op.drop_column("book", "pages")
    # ### end Alembic commands ###
